// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1743126480);
user_pref("browser.search.region", "KR");
user_pref("calendar.caldav.googleResync", 1743126479);
user_pref("calendar.list.sortOrder", "c0c8c4fd-a550-4f94-acf6-c227108c0c47");
user_pref("calendar.registry.c0c8c4fd-a550-4f94-acf6-c227108c0c47.calendar-main-default", true);
user_pref("calendar.registry.c0c8c4fd-a550-4f94-acf6-c227108c0c47.calendar-main-in-composite", true);
user_pref("calendar.registry.c0c8c4fd-a550-4f94-acf6-c227108c0c47.disabled", true);
user_pref("calendar.registry.c0c8c4fd-a550-4f94-acf6-c227108c0c47.name", "Home");
user_pref("calendar.registry.c0c8c4fd-a550-4f94-acf6-c227108c0c47.type", "storage");
user_pref("calendar.registry.c0c8c4fd-a550-4f94-acf6-c227108c0c47.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Seoul");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1743126477);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230214184313");
user_pref("extensions.lastAppVersion", "102.8.0");
user_pref("extensions.lastPlatformVersion", "102.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"341671e6-3c03-4d61-b8b4-70657993aeb2\",\"google@search.mozilla.org\":\"eaf3dd01-eea2-47e9-b98c-f52be1efcb71\",\"ddg@search.mozilla.org\":\"ec67da7e-748c-4ce5-99e3-8635873b2f20\",\"amazon@search.mozilla.org\":\"3705ce91-6ebb-4342-8394-f0cb4f8cc297\",\"chambers-en-GB@search.mozilla.org\":\"3062bac9-d25b-424f-9ba6-00e5cfb17d19\",\"wikipedia@search.mozilla.org\":\"74b80868-7451-48a2-a11a-f89de8061794\",\"bing@search.mozilla.org\":\"e9299a3e-fef5-4aa7-a1f7-c9d8c99c0808\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "e8268af8-f70b-4775-9166-bc2ff0aec31");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.8.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.previousBuildID", "20230214184313");
